language: ruby
cache: bundler

services:
  - redis-server

rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.6
  - 2.2.0
  - 2.2.2

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - virtualstaticvoid@gmail.com
    on_failure: change
    on_success: never

